-- Migration: Create STOCK_MOVEMENTS table
-- This table tracks stock changes (entries and exits) for auditing

-- Create the sequence for auto-increment ID
CREATE SEQUENCE STOCK_MOVEMENTS_SEQ START WITH 1 INCREMENT BY 1;

-- Create the table
CREATE TABLE STOCK_MOVEMENTS (
    ID NUMBER(10) DEFAULT STOCK_MOVEMENTS_SEQ.NEXTVAL PRIMARY KEY,
    PRODUCT_ID NUMBER(10) NOT NULL,
    TYPE VARCHAR2(10) NOT NULL CHECK (TYPE IN ('ENTRY', 'EXIT')),
    QUANTITY NUMBER(10) NOT NULL,
    PREVIOUS_STOCK NUMBER(10) NOT NULL,
    NEW_STOCK NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    REFERENCE VARCHAR2(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_STOCK_MOVEMENTS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

-- Create indexes
CREATE INDEX IX_STOCK_MOVEMENTS_PRODUCT_ID ON STOCK_MOVEMENTS(PRODUCT_ID);
CREATE INDEX IX_STOCK_MOVEMENTS_CREATED_AT ON STOCK_MOVEMENTS(CREATED_AT);

-- Add comments for documentation
COMMENT ON TABLE STOCK_MOVEMENTS IS 'Tracks all stock movements (entries and exits) for auditing purposes';
COMMENT ON COLUMN STOCK_MOVEMENTS.ID IS 'Primary key';
COMMENT ON COLUMN STOCK_MOVEMENTS.PRODUCT_ID IS 'Foreign key to PRODUCTS table';
COMMENT ON COLUMN STOCK_MOVEMENTS.TYPE IS 'Movement type: ENTRY or EXIT';
COMMENT ON COLUMN STOCK_MOVEMENTS.QUANTITY IS 'Quantity moved';
COMMENT ON COLUMN STOCK_MOVEMENTS.PREVIOUS_STOCK IS 'Stock before the movement';
COMMENT ON COLUMN STOCK_MOVEMENTS.NEW_STOCK IS 'Stock after the movement';
COMMENT ON COLUMN STOCK_MOVEMENTS.USER_ID IS 'User who performed the movement';
COMMENT ON COLUMN STOCK_MOVEMENTS.REFERENCE IS 'Reference information (e.g., invoice transaction ID)';
COMMENT ON COLUMN STOCK_MOVEMENTS.CREATED_AT IS 'Timestamp of the movement';
