-- Migration: Create ERROR_LOGS table

-- Create the sequence
CREATE SEQUENCE ERROR_LOGS_SEQ START WITH 1 INCREMENT BY 1;

-- Create the table
CREATE TABLE ERROR_LOGS (
    ID NUMBER(10) DEFAULT ERROR_LOGS_SEQ.NEXTVAL PRIMARY KEY,
    MESSAGE CLOB NOT NULL,
    STACK_TRACE CLOB,
    EXCEPTION_TYPE VARCHAR2(255),
    USER_ID NUMBER(10),
    PATH VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IX_ERROR_LOGS_USER_ID ON ERROR_LOGS(USER_ID);
CREATE INDEX IX_ERROR_LOGS_CREATED_AT ON ERROR_LOGS(CREATED_AT);
